### ISSUE TITLE
dropbox causes panel and system crash

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-indicator-applet#1]
starting dropbox via

dropbox start -i

causes both the panel and whole system to crash.

Workaround: move to a TTY and login

cd ~/.config/autostart
rm dropbox.desktop

use startup applications and start dropbox using the command line

dbus-launch dropbox start -i

**Comment by charlesmilam** [comment]
Experiencing this, and now caught in an endless loop of reboots. Having to use Unity to use system.

**Comment by fossfreedom** [comment]
found the issue - just going to push a fix.

**Comment by fossfreedom** [comment]
ok - an update should stop the crash.

Going to keep this open though for the moment - need to understand why some appindicators are as badly behaved as dropbox and not providing a name describing itself.  For these appindicators we dont show them.

this bug report is relevant:
- https://bugs.launchpad.net/ubuntu/+source/nautilus-dropbox/+bug/1546176

**Comment by charlesmilam** [comment]
While the crashing has stopped, I don't get any type of app indication. Dropbox definitely works in Unity, but don't see any indicator for it with Budgie, nor for Spotify, or any indication of network connectivity.

I installed using apt-get using the remix ppa. I had previously removed it via the same when the crashing began.

I have it installed in the 'End' panel. I do not have the System Tray installed in any panel.

**Comment by fossfreedom** [comment]
I've removed the erroneous note about the system tray  - you will still need that for the moment - especially for dropbox.

Make sure in your startup applications the drop-box command is dbus-launch dropbox start -i

The drop-box icon will appear in the system tray - there is a known bug in 16.04 and later with drop-box where it refuses to work correctly in all ubuntu flavours except unity.

**Comment by charlesmilam** [comment]
Success! Dropbox now loads its app indicator, as does Google chrome.

Thank you for your efforts and prompt responses.

**Comment by fossfreedom** [comment]
closing ... not alot we can do with dropbox - the vendor needs to sort out their mess.
