### ISSUE TITLE
Vertically oriented panel

### ISSUE THREAD

**Issue by beerminer** [UbuntuBudgie/budgie-indicator-applet#10]
Hi again,

I have been using my panel with a vertical orientation (in 17.10 up-to-date) and usually only have an indicator for Dropbox, so I did not notice this earlier.  I opened Shutter, which has an indicator, and it looks like the indicator applet sticks to a horizontal orientation, rather than bumping the new icon below. So the panel changes width when this happens (this is with the updated version of the applet).  I have included before and after pictures:
![screenshot from 2017-09-23 18 24 49](https://user-images.githubusercontent.com/32007100/30778536-346430ca-a08d-11e7-9afa-af51c4307a9c.png)

![screenshot from 2017-09-23 18 25 38](https://user-images.githubusercontent.com/32007100/30778537-3da8d636-a08d-11e7-86e3-2fbc831cdcab.png)

Cheers

**Comment by fossfreedom** [comment]
Can confirm.

I have raised this upstream previously. There is not a direct budgie method to determine if an applet is running in either a vertical or horizontal mode.

We might have to be a bit sneaky and dig around in the background to find that information.

Help wanted to resolve this

**Comment by fossfreedom** [comment]
need to figure out what the C equivalent of the do_ event override here is then we'll have a fighting chance of implementing this.

https://github.com/ilgarmehmetali/budgie-pixel-saver-applet/commit/17ce478d2ce812d8079d2c5fd4945d9f49228378

**Comment by fossfreedom** [comment]
should now be resolved by this commit https://github.com/UbuntuBudgie/budgie-indicator-applet/commit/b5fc51fb466394390d53b810d21429e4043fc0c6
