### ISSUE TITLE
Ayatana Indicator Session integration

### ISSUE THREAD

**Issue by sunweaver** [UbuntuBudgie/budgie-indicator-applet#14]
To fully support the Budgie Desktop Environment in ayatana-indicator-session [1], please let us know the following via our Github issue tracker:

  * XDG_CURRENT_DESKTOP has what value?
  * tool to display information on the computer system
  * how to evoke the logout dialog
  * how to evoke the shutdown dialog
  * how to evoke the reboot dialog
  * how to launch the system settings / control center application
  * how to open your desktop envs user guide

[1] https://github.com/AyatanaIndicators/ayatana-indicator-session

**Comment by fossfreedom** [comment]
XDG_CURRENT_DESKTOP has what value? --> Budgie:GNOME
    tool to display information on the computer system -->  gnome-control-center info-overview
    how to evoke the logout dialog --> gnome-session-quit --logout
    how to evoke the shutdown dialog --> gnome-session-quit --power-off
    how to evoke the reboot dialog --> gnome-session-quit --reboot
    how to launch the system settings / control center application --> gnome-control-center
    how to open your desktop envs user guide --> budgie doesn't have one by default

N.B. Budgie Desktop has a native session applet by default to allow you to logout/lock the screen/restart/shutdown/suspend/hibernate.
