### ISSUE TITLE
Ayatana Indicator Power integration

### ISSUE THREAD

**Issue by sunweaver** [UbuntuBudgie/budgie-indicator-applet#15]
For being able to fully support the Budgie desktop environment in ayatana-indicator-power [1], please tell us the following bits of information:

  * XDG_CURRENT_DESKTOP shows what?
  * how to launch your desktops's power settings dialog
  * how to launch power statistics for your desktop environment (if you have that)

**Comment by sunweaver** [comment]
[1] https://github.com/AyatanaIndicators/ayatana-indicator-power

**Comment by fossfreedom** [comment]
XDG_CURRENT_DESKTOP shows what? --> Budgie:GNOME
    how to launch your desktops's power settings dialog --> gnome-control-center power
    how to launch power statistics for your desktop environment (if you have that) --> gnome-power-statistics

As an aside, Budgie Desktop has a native applet by default that displays the battery level and can invoke the power settings.  It doesn't though launch power statistics.
