### ISSUE TITLE
App Icons don't scale down if panel is under 37px

### ISSUE THREAD

**Issue by SaucySauce** [UbuntuBudgie/budgie-indicator-applet#19]
If the panel size is smaller than 37px the appindicator applet, when triggered/showing app indicator icon, forces the panel to be at least that size.

Decreasing the panel size number results in active windows rendering under the panel itself while remaining at a minimum of 37px if an app indicator is active.

Version: 0.5-0ubuntu2

**Comment by fossfreedom** [comment]
Nothing we can do about that. Appindicator has a min icon size and padding to display stuff.

**Comment by SaucySauce** [comment]
Not possible to lower the minimum icon size to 32?

**Comment by fossfreedom** [comment]
No.

**Comment by SaucySauce** [comment]
Thanks.
