### ISSUE TITLE
The top bar increases height when the Slack icon appears on AppIndicador Applet.

### ISSUE THREAD

**Issue by MessiasLima** [UbuntuBudgie/budgie-indicator-applet#25]
## Description
The top bar increases size when the Slack icon appears on AppIndicador Applet.

## Budgie version
budgie-desktop 10.5.1
Copyright © 2014-2019 Budgie Desktop Developers

## Operating system
Ubuntu Budgie 20.04.1 LTS

## Steps to reproduce the issue
1. Open slack
1. The top panel will increase the size overlapping the windows

## Actual result
<a href="https://www.loom.com/share/e2d8118aad6641bcbfebe5cec1c53a6d"> <p>Loom | Free Screen & Video Recording Software - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/e2d8118aad6641bcbfebe5cec1c53a6d-with-play.gif"> </a>

## Expected result
The panel must maintain the size no matter the size of the icon shown

## Additional information
```
            .-/+oossssoo+/-.               messias@messias-ThinkPad-E580 
        `:+ssssssssssssssssss+:`           ----------------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 20KS001JPG ThinkPad E580 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-47-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 2 hours, 52 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2035 (dpkg), 14 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080, 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Budgie 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter(Budgie) 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Qogir-dark [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Reversal-blue-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: xfce4-terminal 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal Font: MesloLGS NF 10 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i5-8250U (8) @ 3.400GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel UHD Graphics 620 
      -+sssssssssssssssssyyyssss+-         Memory: 4334MiB / 15775MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
                                                                   

```         
- When I change the panel height on Budgie desktop settings, the panel height back to the right height.

**Comment by fossfreedom** [comment]
What is the size of your panel?

**Comment by MessiasLima** [comment]
30px

**Comment by fossfreedom** [comment]
Your panel height is too small.  The app indicator specification allows for icons 16px to 24px. With padding forced by the appindicator itself means your panel must be around 32 to 36px depending upon the theme. Some themes add additional padding. Use a slim variant if possible or remove the appindicator from the panel.

**Comment by MessiasLima** [comment]
But it simply does not make sense. It's normal behaviour for application bars to have less than 30px. GNOME, Plasma, XFCE, Mate.. all this can handle indicators with hight less than 30px. The default size is too big for a global menu like that.

**Comment by MessiasLima** [comment]
What are the alternatives to the indicator applet?

**Comment by fossfreedom** [comment]
If the app in question provides a system tray icon you can use the system
tray applet
