### ISSUE TITLE
the old oversized icon issue is back

### ISSUE THREAD

**Issue by auturgy** [UbuntuBudgie/budgie-indicator-applet#27]
G'day guys.  Loving Budgie, but there's an annoying (although not critical) issue with an oversized icon bloating out the indicator tray on a clean install.  Interestingly, this issue popped up on a clean install to a new machine but wasn't present on my previous machine (also Budgie on U20.04)
It seems this has been reported a number of times, and closed without a proper fix.  From a user (and usability) perspective, it needs to be resolved, so opened a new issue.
In my case the specific app is the Droidcam client - https://www.dev47apps.com/droidcam/linux/
Related: https://github.com/UbuntuBudgie/budgie-indicator-applet/issues/25
https://github.com/UbuntuBudgie/budgie-indicator-applet/issues/19
https://github.com/UbuntuBudgie/budgie-indicator-applet/issues/18
https://github.com/UbuntuBudgie/budgie-indicator-applet/issues/3

**Comment by fossfreedom** [comment]
its fixed in git master and also has been uploaded to 21.10.

**Comment by auturgy** [comment]
Can it be backported?

**Comment by fossfreedom** [comment]
To be considered for a backport I would normally wait until a release has happened to allow alot more people to have eyes on the update to confirm no adverse effects.

At the moment I have had only one confirmation that things are OK.

**Comment by auturgy** [comment]
Bit of a chicken-and-egg argument there, but no worries.
I’ll build master and let you know.

**Comment by auturgy** [comment]
Can confirm fixed in master, on 20.04 base.
