### ISSUE TITLE
some menu icons appear huge in 16.10

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-indicator-applet#3]
From launchpad: https://bugs.launchpad.net/budgie-remix/+bug/1641457

![](https://bugs.launchpad.net/budgie-remix/+bug/1641457/+attachment/4777011/+files/budgie.png)

https://github.com/UbuntuBudgie/budgie-indicator-applet/blob/master/src/applet-main.c

suspect line 242 we should resize the image to a button icon size (approx 16px probably)

**Comment by fossfreedom** [comment]
https://bugs.launchpad.net/ubuntu/+source/wallch/+bug/1313531

icons should be 22x22 in size.

The xfce guys make a strong point not to force the resizing - it has lots of performance issues.

Elementary have worked around this by not using GtkMenuBar but instead a GtkButtonBox.

This is perhaps the better solution we need - its in the TODO list.

**Comment by fossfreedom** [comment]
sledgehammer approach  https://forums.insynchq.com/t/another-indicator-applet-problem/8187/4

**Comment by tushantin** [comment]
I'm also currently affected by this in Ubuntu 16.04, which I unknowingly posted about here: https://github.com/budgie-desktop/budgie-desktop/issues/1131

**Comment by fossfreedom** [comment]
What is spideroak and how do you install it?  It should be installing it icon somewhere. Please let me know where.

**Comment by tushantin** [comment]
@fossfreedom It's a cloud-backup service, you can get the binaries here if you like. https://spideroak.com/one/download/

**Comment by fossfreedom** [comment]
Where is the source? I am not going to install random binaries.

**Comment by tushantin** [comment]
I don't think SpiderOak client itself is opensource. xD

**Comment by fossfreedom** [comment]
Please file a bug with spideroak. Appindicator icons must be 22px in size.

As per xfce comments above I am not going to compromise our appindicator for proprietary software deficiencies.

On 1 Sep 2017 07:04, tushantin <notifications@github.com> wrote:

I don't think SpiderOak client itself is opensource. xD

**Comment by tushantin** [comment]
That's okay, I'm just saying I'm experiencing that icon-oversized issue, and if there's any way I can help (like checking what the nature of the icon is based on where it's installed), please let me know. 

I run multiple desktop environments on my system — Unity, XFCE, Gnome and LXDE — but it's only in Budgie that I have this problem occurring. Everywhere else it's fine.

**Comment by fossfreedom** [comment]
If you can find the icon in /use/share/icons then check it's size

**Comment by Jacob-Vlijm** [comment]
@tushantin Not entirely true, e,g, a .png icon, *outside* one of the dirs where an icon can be called by name (like `/usr/share/pixmaps`), becomes huge in Dash if it is defined *including* path and extension.

**Comment by Jacob-Vlijm** [comment]
@fossfreedom I believe SpiderOak icons are compiled into the binary, then on run stored in a temporary directory.

**Comment by tushantin** [comment]
Looks like there is a smaller SVG icon! But interestingly, I can't seem to find the mono-colored icon in the screenshot I initially linked to, which seems to be the primary source of the issue. There is a PNG icon in `/usr/share/pixmaps`, but that too is in full-color and not the mono-icon that's the subject of concern. 

![selection_688](https://user-images.githubusercontent.com/5314015/29972282-4b88a204-8f49-11e7-87e6-fbf85a914fe3.png)

**Comment by Jacob-Vlijm** [comment]
@tushantin https://askubuntu.com/questions/832568/how-do-i-find-the-icon-files-used-by-non-default-status-menus-aka-indicators/865149 "Exceptional situations".

**Comment by tushantin** [comment]
@Jacob-Vlijm Thanks for the link! Found it! :smiley: And they seem to be... 

....a series of 128px PNG files. :disappointed: Ah, bummer... 

![selection_689](https://user-images.githubusercontent.com/5314015/29972853-35de32a0-8f4b-11e7-8f4a-6b4fe99eb16d.png)

**Comment by Jacob-Vlijm** [comment]
@tushantin  AH, see, a temporary set of icons!

**Comment by fossfreedom** [comment]
speculation - as per https://stackoverflow.com/questions/39946206/gtkcontainer-gtkwidget-maximum-width

maybe connect to the size-allocate signal to the gtk-box holding the app indicator
then use the set-size-request with a -1 value for the width and something like 22 for the height or preferably a GTK constant in this area.

example code http://blog.borovsak.si/2009/05/wrapping-adn-resizing-gtklabel.html

https://www.kksou.com/php-gtk2/sample-codes/set-the-button-to-the-exact-size-you-want-Part-1.php

**Comment by neowiz73** [comment]
one thing I just noticed today is how themes can cause the icons and area to be really large. 
a number of themes contain .menubar > menuitem padding: 4px 6px (or some other number).  the first px setting is the vertical padding, which if it is set anything other than 0, it will cause the appindicator to be larger than expected. it also throws off the panel and causes it to overlap windows.  

this is also the case with the global menu from the vala panel appmenu applet.

**Comment by fossfreedom** [comment]
@neowiz73 interesting observation.

Not sure why themes would have such large padding values - definitely not helpful!

Maybe able to override .menbar .menuitem padding in the code?

Which themes have the large padding values?

**Comment by neowiz73** [comment]
@fossfreedom So far the default built in theme for Raven (Arc, Arc Dark, Arc Darker), Gnome OSX - III, pretty much any theme based on Arc, unless it was specifically changed. 
keep in mind as of gtk3 3.20 forward it's now just menubar > menuitem but gtk3 3.18 and before it is .menubar > menuitem

**Comment by fossfreedom** [comment]
thanks @neowiz73 

still looking for someone inspirational to help with the above.

EDIT: other possible avenues - see if can set a CSS class on the image and set the CSS like this:  `img { max-height: 22px; max-width: 22px; }`

**Comment by fossfreedom** [comment]
@tushantin please can you urgently test a possible fix for your issue ?

    sudo add-apt-repository ppa:ubuntubudgie-dev/test-indicator
    sudo apt update
    sudo apt upgrade

logout and login

when finished testing please remove:

    sudo ppa-purge ppa:ubuntubudgie-dev/test-indicator

let me know if all is well

**Comment by tushantin** [comment]
@fossfreedom Sorry for the delay in my response, but it looks like it works! 

EDIT: I can't purge the PPA, apparently it tells me "sudo: ppa-purge: command not found".

![workspace 1_723](https://user-images.githubusercontent.com/5314015/30514754-19ae1254-9b39-11e7-943a-8e0c73547aa5.png)

**Comment by fossfreedom** [comment]
Thanks

sudo apt install ppa-purge

**Comment by pwnbyte** [comment]
I have the same problem with wire desktop https://wire.com, the icon on status-menu goes bigger when i open the app.. after google.. 
$ sudo add-apt-repository ppa:ubuntubudgie-dev/desktop-icons
$ sudo apt-get update; sudo apt-get upgrade -y;

after i log out.. and login again.. and the bigger icon was removed.. but in the same place this icon.. appears.. like the image bellow... now instead wire icon, has a "monitor" with a red "X" at the botton 

![screenshot from 2019-01-23 19-30-48](https://user-images.githubusercontent.com/44944461/51641885-3a6e7500-1f46-11e9-9c7f-4ffde8443c81.png)

**Comment by fossfreedom** [comment]
@ghostnil report the issue to the software vendor - the large icon is because the vendor is not following the appindicator spec - icons should be 22px in size for a .png or must be in .svg format.
The red x icon is typically another bug with the wire software - probably they are assuming just "unity" - they should NOT assume that.

**Comment by pwnbyte** [comment]
Ok fossfreedom xD sorry for that i'll report now many thanks.. 
and great job with budgie :heart: 

edit: 
someone open a issue :+1: 
https://github.com/wireapp/wire-desktop/issues/2073
