### ISSUE TITLE
System apps not showing; Dropbox is just black square icon

### ISSUE THREAD

**Issue by xmbwd** [UbuntuBudgie/budgie-indicator-applet#4]
This is a great project -- but I can't get it to work.  I installed it in the Budgie panel and removed the system tray.  The result is that (A) I have no system tray icons (e.g., networking) and (B) Dropbox shows up as a black box with a red x at the bottom.  I tried reinstalling Drobpbox, but no joy.  I'm on Budgie 10.2.9.0.

**Comment by fossfreedom** [comment]
please readd the system-tray - you still need it.

For dropbox - this is a dropbox issue itself.  

To workaround this you need to:

copy /etc/xdg/autostart/dropbox.desktop to ~/.config/autostart

change the exec= statement to

exec=dbus-launch dropbox start -i

save.

Then remove the old /etc/xdg/autostart/dropbox.desktop

logout, login

**Comment by xmbwd** [comment]
Thanks for the assist -- I added the systemtray back in.  I removed based on the [OMGUbuntu](http://www.omgubuntu.co.uk/2016/11/budgie-desktop-picks-indicator-applet-support) post.  

I changed the exec statement, but that didn't work.  Here is my dropbox.desktop file:

`[Desktop Entry]
Name=Dropbox
GenericName=File Synchronizer
Comment=Sync your files across computers and to the web
Exec=dbus-launch dropbox start -i
Terminal=false
Type=Application
Icon=dropbox
Categories=Network;FileTransfer;
StartupNotify=false`

**Comment by fossfreedom** [comment]
see my update to my comment above

**Comment by xmbwd** [comment]
Success!  I changed my "startup applications" entry `dbus-launch dropbox start -i`.  Many thanks.

**Comment by joaspacce** [comment]
I changed the entry, but after some reboots the icon shows again as black square again.

 I'm on Budgie 10.2.9.2 in Ubuntu 16.04.2, I added Budgie with ppa:budgie-remix/ppa.

**Comment by fossfreedom** [comment]
@joaspacce if you have copied the .desktop to ~/.local/share/applications and the black square still occurs then rename the file in /usr/share/applications as well (suffix it with .backup).  That way there should only be one .desktop file read - your local version.

**Comment by joaspacce** [comment]
Thanks, Is working well!. Keep making this nice flavor!
