### ISSUE TITLE
dropbox does not display

### ISSUE THREAD

**Issue by fossfreedom** [UbuntuBudgie/budgie-indicator-applet#6]
dropbox only works in Unity - its something dropbox themselves have to fix.

Workaround is to use dbus-launch as per this http://askubuntu.com/questions/732967/dropbox-icon-is-not-working-xubuntu-14-04-lts-64

This issue - if you run 

    env XDG_CURRENT_DESKTOP="Unity" dropbox start -i

dropbox does not display at all - need to debug to see why.

**Comment by fossfreedom** [comment]
resolved now in 17.10

**Comment by vanerleo** [comment]
same issue in 18.04
setting 
```
env XDG_CURRENT_DESKTOP="Unity" dropbox start -i
```
fixed it

**Comment by fossfreedom** [comment]
@vanerleo did you download the .deb directly from dropbox?  Please don't do that.  Their .deb is broken.  Please purge it.  Use budgie-welcome - recommendations and install the dropbox recommendation.

**Comment by vanerleo** [comment]
all worked, thanks

**Comment by owniz** [comment]
@fossfreedom I installed it from budgie-welcome - recommendations and it doesn't show, also I have tried with 

> env XDG_CURRENT_DESKTOP="Unity" dropbox start -i

**Comment by fossfreedom** [comment]
Have you got the appindicator applet added to your panel?

**Comment by owniz** [comment]
@fossfreedom Ups, I thought it was added... Thank you!
