### ISSUE TITLE
background color different than panel

### ISSUE THREAD

**Issue by beerminer** [UbuntuBudgie/budgie-indicator-applet#9]
Hi there,

I am running the Artful dev branch and the appindicator background is not respecting the theme, in this case Adapta.  The background behind the icon is lighter than the panel color, as seen in the screenshot.
![screenshot from 2017-09-15 21 20 04](https://user-images.githubusercontent.com/32007100/30509094-67928172-9a5c-11e7-8be0-6fc6906e85fd.png)

**Comment by fossfreedom** [comment]
Can you test the #3 version of the appindicator please?

**Comment by beerminer** [comment]
Perfect! 
![screenshot from 2017-09-16 07 13 19](https://user-images.githubusercontent.com/32007100/30512924-ba9cea2c-9aae-11e7-96d6-fa63e1d783d3.png)

**Comment by fossfreedom** [comment]
thanks for testing.  it will be uploaded to artful shortly.  thanks
